### ISSUE TITLE
Error when installing on windows: npm ERR!   'cp' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by SyedGhazanferAnwar** [drakedevel/zstd-napi#93]

**Comment by drakedevel** [comment]
@SyedGhazanferAnwar Thanks for the report! Do you have the full build logs available, by any chance?

My best guess is this was a build from source (i.e. prebuilds didn't work), since there's this command in `binding.gyp`:
```python
        'action': ['cp', 'deps/zstd/LICENSE', '<@(_outputs)'],
```

I forgot `cp` wouldn't work on Windows, presumably the build works in CI because GitHub preinstalled something that provides that command to make it more Unix-like.
